<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Event\ProfileEntitySubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Event/ProfileEntitySubscriber.php';

return $this->services['AppBundle\Event\ProfileEntitySubscriber'] = new \AppBundle\Event\ProfileEntitySubscriber($this);
