<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'RandomBundle\Event\UserEntitySubscriber' shared service.

return $this->services['RandomBundle\Event\UserEntitySubscriber'] = new \RandomBundle\Event\UserEntitySubscriber();
