<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Event\GenerateFileSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Event/GenerateFileSubscriber.php';
include_once $this->targetDirs[3].'/src/AppBundle/Managers/FileManager.php';

return $this->services['AppBundle\Event\GenerateFileSubscriber'] = new \AppBundle\Event\GenerateFileSubscriber($this, ${($_ = isset($this->services['AppBundle\Managers\FileManager']) ? $this->services['AppBundle\Managers\FileManager'] : $this->services['AppBundle\Managers\FileManager'] = new \AppBundle\Managers\FileManager($this)) && false ?: '_'});
