<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\ProfileType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/src/AppBundle/Form/ProfileType.php';
include_once $this->targetDirs[3].'/src/AppBundle/Managers/FileManager.php';

return $this->services['AppBundle\Form\ProfileType'] = new \AppBundle\Form\ProfileType($this, ${($_ = isset($this->services['AppBundle\Managers\FileManager']) ? $this->services['AppBundle\Managers\FileManager'] : $this->services['AppBundle\Managers\FileManager'] = new \AppBundle\Managers\FileManager($this)) && false ?: '_'});
