<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZegkh6r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZegkh6r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZegkh6r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZegkh6r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZegkh6r\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zegkh6r',
    'container.build_id' => 'f9a0fe08',
    'container.build_time' => 1527983877,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZegkh6r');
