<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpmlxee\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpmlxee/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMpmlxee.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMpmlxee\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMpmlxee\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mpmlxee',
    'container.build_id' => 'b6f72a61',
    'container.build_time' => 1528299759,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpmlxee');
