<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0rkiris\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0rkiris/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0rkiris.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0rkiris\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0rkiris\appDevDebugProjectContainer(array(
    'container.build_hash' => '0rkiris',
    'container.build_id' => '03594563',
    'container.build_time' => 1527817264,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0rkiris');
